---
name: "ci"

on:
  push:
  pull_request:
    types:
      - "opened"
      - "closed"
      - "reopened"
      - "synchronize"

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v1"
        with:
          lfs: true

      - name: "Build and run tests"
        env:
          JEST_VERBOSE: ${{ secrets.JEST_VERBOSE }}
        run: |
          yarn run reinstall
          yarn run lint
          yarn run test
          yarn run build
      - uses: "./packages/keybase-notifications"
        if: always()
        with:
          job_status: ${{ job.status }}
          opensentinel_owner: ${{ secrets.OSL_OWNER }}
          opensentinel_token: ${{ secrets.OSL_TOKEN }}
